// test_station_parity.cpp -- the board's station logic against the product's.
//
// station_parity_vectors.h is GENERATED by covio/scripts/station-parity-vectors.ts
// from the platform's certified reference (station-logic.ts): every input of
// two dozen scenarios and a long seeded random run, and every output the
// reference produced. Replay each step into station_logic.h and require the
// identical light, sound, beep and event text. One difference fails the run
// and names the scenario, the step and both answers.
//
//   g++ -std=c++14 -O1 -Wall -I. -I../.. test_station_parity.cpp -o parity && ./parity
#include <stdio.h>
#include <string.h>

#include "station_logic.h"
#include "station_parity_vectors.h"

using namespace station;

static Config g_live;
static Config g_scratch;

static void joinEvents(const TickOutput& o, char* buf, size_t len) {
  buf[0] = 0;
  size_t used = 0;
  for (int i = 0; i < o.eventCount; i++) {
    char one[160];
    eventText(o.events[i], one, sizeof(one));
    used += (size_t)snprintf(buf + used, len - used, "%s%s", i ? ";" : "", one);
  }
}

int main() {
  int failures = 0;
  unsigned long steps = 0;
  for (uint32_t s = 0; s < PV_SCENARIO_COUNT; s++) {
    const PvScenario& sc = PV_SCENARIOS[s];
    StationLogic logic(&g_live);
    int scenarioFailures = 0;
    for (uint32_t i = 0; i < sc.count && scenarioFailures < 3; i++) {
      const PvStep& st = sc.steps[i];
      steps++;
      if (st.kind == 2) {
        logic.boot(st.ack != 0);
        continue;
      }
      char got[1024];
      if (st.kind == 1) {
        Event e = logic.applyConfig(st.body, &g_scratch);
        eventText(e, got, sizeof(got));
        if (strcmp(got, st.events) != 0) {
          printf("FAIL [%s] step %u config: want \"%s\" got \"%s\"\n", sc.name, i, st.events, got);
          scenarioFailures++;
        }
        continue;
      }
      TickInput in;
      in.uptimeS = st.t;
      in.hasWall = st.wall >= 0;
      in.wallMs = st.wall;
      in.pulses = st.pulses;
      in.total = st.total;
      in.tap = st.tap;
      in.readerUp = st.reader != 0;
      in.inputSuspect = st.suspect != 0;
      in.outputFault = st.fault != 0;
      TickOutput out;
      logic.tick(in, &out);
      joinEvents(out, got, sizeof(got));
      if (out.light != st.light || (out.sounding ? 1 : 0) != st.sounding || out.beep != st.beep ||
          strcmp(got, st.events) != 0) {
        printf(
            "FAIL [%s] step %u t=%u: want light=%u sound=%u beep=%u \"%s\"\n"
            "                          got  light=%u sound=%u beep=%u \"%s\"\n",
            sc.name, i, st.t, st.light, st.sounding, st.beep, st.events, out.light,
            out.sounding ? 1 : 0, out.beep, got);
        scenarioFailures++;
      }
    }
    if (scenarioFailures) failures += scenarioFailures;
    printf("%s  %s (%u steps)\n", scenarioFailures ? "FAIL" : "ok  ", sc.name, sc.count);
  }
  printf("\n%u scenarios, %lu steps, %d failure(s)\n", PV_SCENARIO_COUNT, steps, failures);
  return failures ? 1 : 0;
}
