// ============================================================================
// ota_keys.h — RISK-16 remediation: OTA manifest signature verification key
// ----------------------------------------------------------------------------
// Same pattern as certs.h (ADR-005's pinned CA cert), applied to OTA
// manifest authenticity: the device holds ONLY a PUBLIC verification key.
// The corresponding PRIVATE signing key never exists in this firmware, this
// repository, or any CI log -- it is operational key-management material
// held by whoever is authorized to cut Covio releases, exactly matching
// ADR-005's own already-established "signing keys generated and held by
// Covio, never distributed to the field or committed to source control"
// discipline, now applied to firmware-release signing instead of just TLS.
//
// Algorithm: ECDSA over the NIST P-256 curve (secp256r1), SHA-256 digest --
// chosen because ESP-IDF's bundled mbedTLS (already linked into every build
// via WiFiClientSecure's own TLS usage -- confirmed present at
// tools/sdk/esp32s3/include/mbedtls/mbedtls/include/mbedtls/{pk,ecdsa,sha256}.h)
// supports it natively via mbedtls_pk_verify(), with no new library
// dependency. 256-bit curve, ~128-bit security level -- an appropriate,
// widely-used choice for firmware signing (the same curve TLS itself
// commonly uses).
//
// THIS FILE SHIPS WITH A PLACEHOLDER TEST KEY, NOT A REAL PRODUCTION KEY.
// Before any field/release build:
//   1. Replace COVIO_OTA_PUBLIC_KEY_PEM below with the real production
//      public key (generated and held by Covio's release process).
//   2. Set a real COVIO_OTA_KEY_ID (see below) matching the key actually
//      used to sign releases.
//   3. Change COVIO_OTA_KEY_IS_PLACEHOLDER from 1 to 0.
// A RELEASE_BUILD=1 build with the placeholder still in place fails to
// compile outright (same fail-closed pattern as certs.h) -- see the #error
// guard below.
//
// The placeholder key below IS a real, validly-formed ECDSA P-256 public
// key (not a dummy string) -- generated by
// server/tools/sign_manifest.py --gen-test-key specifically for automated
// and isolated hardware testing, per this mandate's explicit instruction to
// "use a temporary non-production signing key for automated and isolated
// hardware tests." The corresponding PRIVATE key for this specific
// placeholder is NOT committed anywhere in this repository -- see
// Docs/audit/coviu_oil_meter_p0_remediation_phase2/21_SIGNING_KEY_MANAGEMENT_PLAN.md
// for exactly where it does live (a local, gitignored file, regenerable by
// anyone running the signing tool with --gen-test-key).
// ============================================================================
#pragma once
#include "config.h"

#define COVIO_OTA_KEY_IS_PLACEHOLDER 1

// Key identifier -- allows a future signed manifest to name WHICH public
// key it expects the device to verify against (supports key rotation:
// multiple trusted keys could be compiled in, keyed by this same id scheme
// -- see 21_SIGNING_KEY_MANAGEMENT_PLAN.md's rotation section for why only
// ONE is implemented this pass, not a trust-list).
#define COVIO_OTA_KEY_ID "covio-test-key-2026-07"

// PLACEHOLDER TEST KEY -- see this file's header comment. Regenerate via:
//   python server/tools/sign_manifest.py --gen-test-key
// TEST KEY, generated this session via `python server/tools/sign_manifest.py
// --gen-test-key` -- REPLACE with the real production public key before any
// RELEASE_BUILD=1 image (the #error guard below already enforces this).
// The corresponding PRIVATE key lives ONLY at the local, gitignored
// server/tools/.test_signing_key.pem -- never committed, never printed in
// full anywhere in this repository or its documentation.
static const char* COVIO_OTA_PUBLIC_KEY_PEM = R"PEMKEY(
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAElDhadjtlgLnDLPz2XkdjJa+GXPUs
jngxaMpIaQspSdkFOaQ77/CBddLU/HNZPFeZpngRfFeMYnbWbUJImgM4Kw==
-----END PUBLIC KEY-----
)PEMKEY";

#if RELEASE_BUILD && COVIO_OTA_KEY_IS_PLACEHOLDER
#error "RELEASE_BUILD=1 but ota_keys.h still has the placeholder OTA signing public key -- replace COVIO_OTA_PUBLIC_KEY_PEM with the real production key (and flip COVIO_OTA_KEY_IS_PLACEHOLDER to 0) before building a release image (RISK-16 / ADR-005 precedent)."
#endif
